package starwars_arre;
/**@author Gustavo_Castillo*/
public class Starwars_Arre {
    public static void main(String[] args) {
        String m [] = new String [3];
        m[0]= "Luke Skywalker";
        m[1] = "172";
        m[2] = "male";
        String cadena = "Luke Skywalker";
        String cadena1 = "male ";
        String cadena2 = "es de estatura baja";
        System.out.println(String.format("%-35s", cadena) + " |  "+ cadena1 +  " " +  "|"  + cadena2);
      String m1 [] = new String [3];
        m1[0] = "Darth vader";
        m1[1] = "202";
        m1[2] = "male";
        String cade = "Darth vader";
        String cade1 = "male ";
        String cade2 = " es de estatura alta";
        System.out.println(String.format("%-35s", cade) + " |  " + cade1 +     " " +  "|" +  cade2);
        String m2 [] = new String [3];
        m2[0] = "Leia Organa";
        m2[1] = "150";
        m2[2] = "female";
        String cad = "Leia Organa";
        String cad1 = "female ";
        String cad2 = " es de estatura baja";
        System.out.println(String.format("%-35s", cad) + " |  " + cad1 +       " "  +   "|" + cad2);
        String m3 [] = new String [3];
        m3[0] = "Owen Lars";
        m3[1] = "178";
        m3[2] = "male";
        String ca = "Owen Lars";
        String ca1 = "male ";
        String ca2 = "es de estatura baja";
        System.out.println(String.format("%-35s", ca) + " |  "+ca1 +           " "  +  "|" +ca2);
        String m4 [] = new String [3];
        m4[0] = "Beru Whitesum lars";
        m4[1] = "165";
        m4[2] = "female";
        String c = "Beru Whitesum lars ";
        String c1 = "female ";
        String c2 = " es de estatura baja";
        System.out.println(String.format("%-35s", c) + " |  " + c1 +           " " +  "|" +c2 );
        String m5 [] = new String [3];
        m5[0] = "Biggs Darklighter";
        m5[1] = "183";
        m5[2] = "male";
        String Cadena = "Biggs Darklighter";
        String Cadena1 = "male ";
        String Cadena2 = " es de estatura baja";
        System.out.println(String.format("%-35s", Cadena) + " |  "+Cadena1 +   " "  +  "|" +Cadena2);
        String m6 [] = new String [3];
        m6[0] = "Obi-Wan Kenobi";
        m6[1] = "182";
        m6[2] = "male";
        String Caden = "Obi-Wan Kenobi";
        String Caden1 = "male ";
        String Caden2 = " es de estatura baja";
        System.out.println(String.format("%-35s", Caden) + " |  "+Caden1 +     " "  + "|" +Caden2);
        String m7 [] = new String [3];
        m7[0] = "Yoda";
        m7[1] = "66";
        m7[2] = "male";
        String Cade = "Yoda";
        String Cade1 = "male ";
        String Cade2 = "es de estatura muy baja";
        System.out.println(String.format("%-35s", Cade) + " |  " + Cade1 +     " " +   "|" +Cade2);
        String m8 [] = new String [3];
        m8[0] = "Jek Tono Porkins";
        m8[1] = "180";
        m8[2] = "male";
        String Cad = "Jek Tono Porkins";
        String Cad1 = "male ";
        String Cad2 = "es de estatura baja";
        System.out.println(String.format("%-35s", Cad) + " |  "+ Cad1 +        " " +  "|" +Cad2);
        String m9 [] = new String [3];
        m9[0] = "Jabba Desilijic Tiure";
        m9[1] = "175";
        m9[2] = "hermaphrodite";
        String Ca = "Jabba Desilijic Tiure";
        String Ca1 = "hermaphrodite";
        String Ca2 = "es de estatura baja";
        System.out.println(String.format("%-35s", Ca) + " |  "+ Ca1 +          " "  +  "|" +Ca2);
        String m10 [] = new String [3];
        m10[0] = "Han solo";
        m10[1] = "180";
        m10[2] = "male";
        String C = "Han solo";
        String C1 = "male ";
        String C2 = "es de estatura baja";
        System.out.println(String.format("%-35s", C) + " |  "+ C1 +            " "  +    "|" + C2);
        String m11 [] = new String [3];
        m11[0] = "Chewbacca";
        m11[1] = "228";
        m11[2] = "male";
        String CADENA = "Chewbacca";
        String CADENA1 = "male ";
        String CADENA2 = "es de estatura muy alta";
        System.out.println(String.format("%-35s", CADENA) + " |  "+CADENA1 +   " "  +  "|" + CADENA2);
        String m12 [] = new String [3];
        m12[0] = "Anakin Skywalker";
        m12[1] = "188";
        m12[2] = "male";
        String CADEN = "Anakin Skywalker";
        String CADEN1 = "male ";
        String CADEN2 = "es de estatura baja";
        System.out.println(String.format("%-35s", CADEN) + " |  "+CADEN1 +     " "  +  "|" + CADEN2);
        String m13 [] = new String [2];
        m13[0] = "R2-D2";
        m13[1] = "96";
        String CADE = "R2-D2";
        String CADE1 = "es de estatura muy baja";
        System.out.println(String.format("%-35s", CADE) + " |  "+CADE1);
        String m14 [] = new String [2];
        m14[0] = "C-3PO";
        m14[1] = "167";
        String CAD = "C-3PO";
        String CAD1 = "es de estatura baja";
        System.out.println(String.format("%-35s", CAD) + " |  "+CAD1);
        String m15 [] = new String [2];
        m15[0] = "R5-D4";
        m15[1] = "97";
        String CA = "R5-D4";
        String CA1 = "es de estatura muy baja";
        System.out.println(String.format("%-35s", CA) + " |  "+CA1);
        System.out.println("--------------------------------------------------");
        double [] altu = new double [16] ;
        altu[0] = 1.72 ;
        altu[1] = 2.02;
        altu[2] = 1.50;
        altu[3] = 1.78;
        altu[4] = 1.65;
        altu[5] = 1.83;
        altu[6] = 1.82;
        altu[7] = 66;
        altu[8] = 1.80;
        altu[9] = 1.75;
        altu[10] = 1.80;
        altu[11] = 2.28;
        altu[12] = 1.88;
        altu[13] = 96;
        altu[14] = 1.67;
        altu[15] = 97;
          for (int i = 0; i<16; i++){
        System.out.println(altu[i]);
        }
        double suma = 0;
        for (int i = 0; i<16; i++){
        suma = suma + altu[i];
        }
        System.out.println("La suma de las alturas es:" + suma);
    }
}